"""SnakeROS message definitions for ``builtin_interfaces``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg

class Duration(Msg):
    _package_ = "builtin_interfaces"
    _kind_ = "msg"
    _name_ = "Duration"
    _fields_ = (
        ("sec", 'i'),
        ("nanosec", 'I'),
    )


class Time(Msg):
    _package_ = "builtin_interfaces"
    _kind_ = "msg"
    _name_ = "Time"
    _fields_ = (
        ("sec", 'i'),
        ("nanosec", 'I'),
    )
