"""SnakeROS message definitions for ``geometry_msgs``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg
from . import std_msgs as _std_msgs

class Vector3(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Vector3"
    _fields_ = (
        ("x", 'd'),
        ("y", 'd'),
        ("z", 'd'),
    )


class Accel(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Accel"
    _fields_ = (
        ("linear", Vector3),
        ("angular", Vector3),
    )


class AccelStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "AccelStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("accel", Accel),
    )


class AccelWithCovariance(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "AccelWithCovariance"
    _fields_ = (
        ("accel", Accel),
        ("covariance", ('a', 'd', 36)),
    )


class AccelWithCovarianceStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "AccelWithCovarianceStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("accel", AccelWithCovariance),
    )


class Inertia(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Inertia"
    _fields_ = (
        ("m", 'd'),
        ("com", Vector3),
        ("ixx", 'd'),
        ("ixy", 'd'),
        ("ixz", 'd'),
        ("iyy", 'd'),
        ("iyz", 'd'),
        ("izz", 'd'),
    )


class InertiaStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "InertiaStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("inertia", Inertia),
    )


class Point(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Point"
    _fields_ = (
        ("x", 'd'),
        ("y", 'd'),
        ("z", 'd'),
    )


class Point32(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Point32"
    _fields_ = (
        ("x", 'f'),
        ("y", 'f'),
        ("z", 'f'),
    )


class PointStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PointStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("point", Point),
    )


class Polygon(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Polygon"
    _fields_ = (
        ("points", ('q', Point32)),
    )


class PolygonInstance(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PolygonInstance"
    _fields_ = (
        ("polygon", Polygon),
        ("id", 'l'),
    )


class PolygonInstanceStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PolygonInstanceStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("polygon", PolygonInstance),
    )


class PolygonStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PolygonStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("polygon", Polygon),
    )


class Quaternion(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Quaternion"
    _fields_ = (
        ("x", 'd'),
        ("y", 'd'),
        ("z", 'd'),
        ("w", 'd'),
    )


class Pose(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Pose"
    _fields_ = (
        ("position", Point),
        ("orientation", Quaternion),
    )


class Pose2D(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Pose2D"
    _fields_ = (
        ("x", 'd'),
        ("y", 'd'),
        ("theta", 'd'),
    )


class PoseArray(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PoseArray"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("poses", ('q', Pose)),
    )


class PoseStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PoseStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("pose", Pose),
    )


class PoseWithCovariance(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PoseWithCovariance"
    _fields_ = (
        ("pose", Pose),
        ("covariance", ('a', 'd', 36)),
    )


class PoseWithCovarianceStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "PoseWithCovarianceStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("pose", PoseWithCovariance),
    )


class QuaternionStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "QuaternionStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("quaternion", Quaternion),
    )


class Transform(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Transform"
    _fields_ = (
        ("translation", Vector3),
        ("rotation", Quaternion),
    )


class TransformStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "TransformStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("child_frame_id", 'T'),
        ("transform", Transform),
    )


class Twist(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Twist"
    _fields_ = (
        ("linear", Vector3),
        ("angular", Vector3),
    )


class TwistStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "TwistStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("twist", Twist),
    )


class TwistWithCovariance(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "TwistWithCovariance"
    _fields_ = (
        ("twist", Twist),
        ("covariance", ('a', 'd', 36)),
    )


class TwistWithCovarianceStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "TwistWithCovarianceStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("twist", TwistWithCovariance),
    )


class Vector3Stamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Vector3Stamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("vector", Vector3),
    )


class VelocityStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "VelocityStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("body_frame_id", 'T'),
        ("reference_frame_id", 'T'),
        ("velocity", Twist),
    )


class VelocityWithCovarianceStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "VelocityWithCovarianceStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("body_frame_id", 'T'),
        ("reference_frame_id", 'T'),
        ("velocity", TwistWithCovariance),
    )


class Wrench(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "Wrench"
    _fields_ = (
        ("force", Vector3),
        ("torque", Vector3),
    )


class WrenchStamped(Msg):
    _package_ = "geometry_msgs"
    _kind_ = "msg"
    _name_ = "WrenchStamped"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("wrench", Wrench),
    )
