"""SnakeROS message definitions for ``nav_msgs``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg
from . import geometry_msgs as _geometry_msgs
from . import std_msgs as _std_msgs

class Odometry(Msg):
    _package_ = "nav_msgs"
    _kind_ = "msg"
    _name_ = "Odometry"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("child_frame_id", 'T'),
        ("pose", _geometry_msgs.PoseWithCovariance),
        ("twist", _geometry_msgs.TwistWithCovariance),
    )


class Path(Msg):
    _package_ = "nav_msgs"
    _kind_ = "msg"
    _name_ = "Path"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("poses", ('q', _geometry_msgs.PoseStamped)),
    )
