"""SnakeROS message definitions for ``rcl_interfaces``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg

class DescribeParameters_Request(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "DescribeParameters_Request"
    _fields_ = (
        ("names", ('q', 'T')),
    )


class FloatingPointRange(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "FloatingPointRange"
    _fields_ = (
        ("from_value", 'd'),
        ("to_value", 'd'),
        ("step", 'd'),
    )


class IntegerRange(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "IntegerRange"
    _fields_ = (
        ("from_value", 'l'),
        ("to_value", 'l'),
        ("step", 'L'),
    )


class ParameterDescriptor(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ParameterDescriptor"
    _fields_ = (
        ("name", 'T'),
        ("type", 'o'),
        ("description", 'T'),
        ("additional_constraints", 'T'),
        ("read_only", 'b'),
        ("dynamic_typing", 'b'),
        ("floating_point_range", ('q', FloatingPointRange)),
        ("integer_range", ('q', IntegerRange)),
    )


class DescribeParameters_Response(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "DescribeParameters_Response"
    _fields_ = (
        ("descriptors", ('q', ParameterDescriptor)),
    )


class GetParameterTypes_Request(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "GetParameterTypes_Request"
    _fields_ = (
        ("names", ('q', 'T')),
    )


class GetParameterTypes_Response(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "GetParameterTypes_Response"
    _fields_ = (
        ("types", ('q', 'o')),
    )


class GetParameters_Request(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "GetParameters_Request"
    _fields_ = (
        ("names", ('q', 'T')),
    )


class ParameterValue(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ParameterValue"
    _fields_ = (
        ("type", 'o'),
        ("bool_value", 'b'),
        ("integer_value", 'l'),
        ("double_value", 'd'),
        ("string_value", 'T'),
        ("byte_array_value", ('q', 'o')),
        ("bool_array_value", ('q', 'b')),
        ("integer_array_value", ('q', 'l')),
        ("double_array_value", ('q', 'd')),
        ("string_array_value", ('q', 'T')),
    )


class GetParameters_Response(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "GetParameters_Response"
    _fields_ = (
        ("values", ('q', ParameterValue)),
    )


class ListParametersResult(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ListParametersResult"
    _fields_ = (
        ("names", ('q', 'T')),
        ("prefixes", ('q', 'T')),
    )


class ListParameters_Request(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "ListParameters_Request"
    DEPTH_RECURSIVE = 0
    _fields_ = (
        ("prefixes", ('q', 'T')),
        ("depth", 'L'),
    )


class ListParameters_Response(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "ListParameters_Response"
    _fields_ = (
        ("result", ListParametersResult),
    )


class Parameter(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "Parameter"
    _fields_ = (
        ("name", 'T'),
        ("value", ParameterValue),
    )


class ParameterType(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ParameterType"
    PARAMETER_NOT_SET = 0
    PARAMETER_BOOL = 1
    PARAMETER_INTEGER = 2
    PARAMETER_DOUBLE = 3
    PARAMETER_STRING = 4
    PARAMETER_BYTE_ARRAY = 5
    PARAMETER_BOOL_ARRAY = 6
    PARAMETER_INTEGER_ARRAY = 7
    PARAMETER_DOUBLE_ARRAY = 8
    PARAMETER_STRING_ARRAY = 9
    _fields_ = ()


class SetParametersAtomically_Request(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "SetParametersAtomically_Request"
    _fields_ = (
        ("parameters", ('q', Parameter)),
    )


class SetParametersResult(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "SetParametersResult"
    _fields_ = (
        ("successful", 'b'),
        ("reason", 'T'),
    )


class SetParametersAtomically_Response(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "SetParametersAtomically_Response"
    _fields_ = (
        ("result", SetParametersResult),
    )


class SetParameters_Request(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "SetParameters_Request"
    _fields_ = (
        ("parameters", ('q', Parameter)),
    )


class SetParameters_Response(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "srv"
    _name_ = "SetParameters_Response"
    _fields_ = (
        ("results", ('q', SetParametersResult)),
    )


class DescribeParameters:
    """Service type: pairs the request and response messages."""
    _package_ = "rcl_interfaces"
    _name_ = "DescribeParameters"
    Request = DescribeParameters_Request
    Response = DescribeParameters_Response


class GetParameterTypes:
    """Service type: pairs the request and response messages."""
    _package_ = "rcl_interfaces"
    _name_ = "GetParameterTypes"
    Request = GetParameterTypes_Request
    Response = GetParameterTypes_Response


class GetParameters:
    """Service type: pairs the request and response messages."""
    _package_ = "rcl_interfaces"
    _name_ = "GetParameters"
    Request = GetParameters_Request
    Response = GetParameters_Response


class ListParameters:
    """Service type: pairs the request and response messages."""
    _package_ = "rcl_interfaces"
    _name_ = "ListParameters"
    Request = ListParameters_Request
    Response = ListParameters_Response


class SetParameters:
    """Service type: pairs the request and response messages."""
    _package_ = "rcl_interfaces"
    _name_ = "SetParameters"
    Request = SetParameters_Request
    Response = SetParameters_Response


class SetParametersAtomically:
    """Service type: pairs the request and response messages."""
    _package_ = "rcl_interfaces"
    _name_ = "SetParametersAtomically"
    Request = SetParametersAtomically_Request
    Response = SetParametersAtomically_Response
