"""SnakeROS message definitions for ``rcl_interfaces``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg

class FloatingPointRange(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "FloatingPointRange"
    _fields_ = (
        ("from_value", 'd'),
        ("to_value", 'd'),
        ("step", 'd'),
    )


class IntegerRange(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "IntegerRange"
    _fields_ = (
        ("from_value", 'l'),
        ("to_value", 'l'),
        ("step", 'L'),
    )


class ListParametersResult(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ListParametersResult"
    _fields_ = (
        ("names", ('q', 'T')),
        ("prefixes", ('q', 'T')),
    )


class ParameterValue(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ParameterValue"
    _fields_ = (
        ("type", 'o'),
        ("bool_value", 'b'),
        ("integer_value", 'l'),
        ("double_value", 'd'),
        ("string_value", 'T'),
        ("byte_array_value", ('q', 'o')),
        ("bool_array_value", ('q', 'b')),
        ("integer_array_value", ('q', 'l')),
        ("double_array_value", ('q', 'd')),
        ("string_array_value", ('q', 'T')),
    )


class Parameter(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "Parameter"
    _fields_ = (
        ("name", 'T'),
        ("value", ParameterValue),
    )


class ParameterDescriptor(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ParameterDescriptor"
    _fields_ = (
        ("name", 'T'),
        ("type", 'o'),
        ("description", 'T'),
        ("additional_constraints", 'T'),
        ("read_only", 'b'),
        ("dynamic_typing", 'b'),
        ("floating_point_range", ('q', FloatingPointRange)),
        ("integer_range", ('q', IntegerRange)),
    )


class ParameterType(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "ParameterType"
    PARAMETER_NOT_SET = 0
    PARAMETER_BOOL = 1
    PARAMETER_INTEGER = 2
    PARAMETER_DOUBLE = 3
    PARAMETER_STRING = 4
    PARAMETER_BYTE_ARRAY = 5
    PARAMETER_BOOL_ARRAY = 6
    PARAMETER_INTEGER_ARRAY = 7
    PARAMETER_DOUBLE_ARRAY = 8
    PARAMETER_STRING_ARRAY = 9
    _fields_ = ()


class SetParametersResult(Msg):
    _package_ = "rcl_interfaces"
    _kind_ = "msg"
    _name_ = "SetParametersResult"
    _fields_ = (
        ("successful", 'b'),
        ("reason", 'T'),
    )
