"""SnakeROS message definitions for ``sensor_msgs``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg
from . import geometry_msgs as _geometry_msgs
from . import std_msgs as _std_msgs

class BatteryState(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "BatteryState"
    POWER_SUPPLY_STATUS_UNKNOWN = 0
    POWER_SUPPLY_STATUS_CHARGING = 1
    POWER_SUPPLY_STATUS_DISCHARGING = 2
    POWER_SUPPLY_STATUS_NOT_CHARGING = 3
    POWER_SUPPLY_STATUS_FULL = 4
    POWER_SUPPLY_HEALTH_UNKNOWN = 0
    POWER_SUPPLY_HEALTH_GOOD = 1
    POWER_SUPPLY_HEALTH_OVERHEAT = 2
    POWER_SUPPLY_HEALTH_DEAD = 3
    POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4
    POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5
    POWER_SUPPLY_HEALTH_COLD = 6
    POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7
    POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8
    POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0
    POWER_SUPPLY_TECHNOLOGY_NIMH = 1
    POWER_SUPPLY_TECHNOLOGY_LION = 2
    POWER_SUPPLY_TECHNOLOGY_LIPO = 3
    POWER_SUPPLY_TECHNOLOGY_LIFE = 4
    POWER_SUPPLY_TECHNOLOGY_NICD = 5
    POWER_SUPPLY_TECHNOLOGY_LIMN = 6
    POWER_SUPPLY_TECHNOLOGY_TERNARY = 7
    POWER_SUPPLY_TECHNOLOGY_VRLA = 8
    _fields_ = (
        ("header", _std_msgs.Header),
        ("voltage", 'f'),
        ("temperature", 'f'),
        ("current", 'f'),
        ("charge", 'f'),
        ("capacity", 'f'),
        ("design_capacity", 'f'),
        ("percentage", 'f'),
        ("power_supply_status", 'o'),
        ("power_supply_health", 'o'),
        ("power_supply_technology", 'o'),
        ("present", 'b'),
        ("cell_voltage", ('q', 'f')),
        ("cell_temperature", ('q', 'f')),
        ("location", 'T'),
        ("serial_number", 'T'),
    )


class FluidPressure(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "FluidPressure"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("fluid_pressure", 'd'),
        ("variance", 'd'),
    )


class Illuminance(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "Illuminance"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("illuminance", 'd'),
        ("variance", 'd'),
    )


class Imu(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "Imu"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("orientation", _geometry_msgs.Quaternion),
        ("orientation_covariance", ('a', 'd', 9)),
        ("angular_velocity", _geometry_msgs.Vector3),
        ("angular_velocity_covariance", ('a', 'd', 9)),
        ("linear_acceleration", _geometry_msgs.Vector3),
        ("linear_acceleration_covariance", ('a', 'd', 9)),
    )


class JointState(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "JointState"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("name", ('q', 'T')),
        ("position", ('q', 'd')),
        ("velocity", ('q', 'd')),
        ("effort", ('q', 'd')),
    )


class Joy(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "Joy"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("axes", ('q', 'f')),
        ("buttons", ('q', 'i')),
    )


class LaserScan(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "LaserScan"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("angle_min", 'f'),
        ("angle_max", 'f'),
        ("angle_increment", 'f'),
        ("time_increment", 'f'),
        ("scan_time", 'f'),
        ("range_min", 'f'),
        ("range_max", 'f'),
        ("ranges", ('q', 'f')),
        ("intensities", ('q', 'f')),
    )


class MagneticField(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "MagneticField"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("magnetic_field", _geometry_msgs.Vector3),
        ("magnetic_field_covariance", ('a', 'd', 9)),
    )


class NavSatStatus(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "NavSatStatus"
    STATUS_UNKNOWN = -2
    STATUS_NO_FIX = -1
    STATUS_FIX = 0
    STATUS_SBAS_FIX = 1
    STATUS_GBAS_FIX = 2
    SERVICE_UNKNOWN = 0
    SERVICE_GPS = 1
    SERVICE_GLONASS = 2
    SERVICE_COMPASS = 4
    SERVICE_GALILEO = 8
    _fields_ = (
        ("status", '1'),
        ("service", 'S'),
    )


class NavSatFix(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "NavSatFix"
    COVARIANCE_TYPE_UNKNOWN = 0
    COVARIANCE_TYPE_APPROXIMATED = 1
    COVARIANCE_TYPE_DIAGONAL_KNOWN = 2
    COVARIANCE_TYPE_KNOWN = 3
    _fields_ = (
        ("header", _std_msgs.Header),
        ("status", NavSatStatus),
        ("latitude", 'd'),
        ("longitude", 'd'),
        ("altitude", 'd'),
        ("position_covariance", ('a', 'd', 9)),
        ("position_covariance_type", 'o'),
    )


class Range(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "Range"
    ULTRASOUND = 0
    INFRARED = 1
    _fields_ = (
        ("header", _std_msgs.Header),
        ("radiation_type", 'o'),
        ("field_of_view", 'f'),
        ("min_range", 'f'),
        ("max_range", 'f'),
        ("range", 'f'),
        ("variance", 'f'),
    )


class Temperature(Msg):
    _package_ = "sensor_msgs"
    _kind_ = "msg"
    _name_ = "Temperature"
    _fields_ = (
        ("header", _std_msgs.Header),
        ("temperature", 'd'),
        ("variance", 'd'),
    )
