"""SnakeROS message definitions for ``std_srvs``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg

class Empty_Request(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Empty_Request"
    _fields_ = ()


class Empty_Response(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Empty_Response"
    _fields_ = ()


class SetBool_Request(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "SetBool_Request"
    _fields_ = (
        ("data", 'b'),
    )


class SetBool_Response(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "SetBool_Response"
    _fields_ = (
        ("success", 'b'),
        ("message", 'T'),
    )


class Trigger_Request(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Trigger_Request"
    _fields_ = (
        ("success", 'b'),
        ("message", 'T'),
    )


class Trigger_Response(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Trigger_Response"
    _fields_ = ()


class Empty:
    """Service type: pairs the request and response messages."""
    _package_ = "std_srvs"
    _name_ = "Empty"
    Request = Empty_Request
    Response = Empty_Response


class SetBool:
    """Service type: pairs the request and response messages."""
    _package_ = "std_srvs"
    _name_ = "SetBool"
    Request = SetBool_Request
    Response = SetBool_Response


class Trigger:
    """Service type: pairs the request and response messages."""
    _package_ = "std_srvs"
    _name_ = "Trigger"
    Request = Trigger_Request
    Response = Trigger_Response
