"""SnakeROS message definitions for ``std_msgs``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg
from . import builtin_interfaces as _builtin_interfaces

class Bool(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Bool"
    _fields_ = (
        ("data", 'b'),
    )


class Byte(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Byte"
    _fields_ = (
        ("data", 'o'),
    )


class MultiArrayDimension(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "MultiArrayDimension"
    _fields_ = (
        ("label", 'T'),
        ("size", 'I'),
        ("stride", 'I'),
    )


class MultiArrayLayout(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "MultiArrayLayout"
    _fields_ = (
        ("dim", ('q', MultiArrayDimension)),
        ("data_offset", 'I'),
    )


class ByteMultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "ByteMultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'o')),
    )


class Char(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Char"
    _fields_ = (
        ("data", 'c'),
    )


class ColorRGBA(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "ColorRGBA"
    _fields_ = (
        ("r", 'f'),
        ("g", 'f'),
        ("b", 'f'),
        ("a", 'f'),
    )


class Empty(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Empty"
    _fields_ = ()


class Float32(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Float32"
    _fields_ = (
        ("data", 'f'),
    )


class Float32MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Float32MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'f')),
    )


class Float64(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Float64"
    _fields_ = (
        ("data", 'd'),
    )


class Float64MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Float64MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'd')),
    )


class Header(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Header"
    _fields_ = (
        ("stamp", _builtin_interfaces.Time),
        ("frame_id", 'T'),
    )


class Int16(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int16"
    _fields_ = (
        ("data", 's'),
    )


class Int16MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int16MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 's')),
    )


class Int32(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int32"
    _fields_ = (
        ("data", 'i'),
    )


class Int32MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int32MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'i')),
    )


class Int64(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int64"
    _fields_ = (
        ("data", 'l'),
    )


class Int64MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int64MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'l')),
    )


class Int8(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int8"
    _fields_ = (
        ("data", '1'),
    )


class Int8MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "Int8MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', '1')),
    )


class String(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "String"
    _fields_ = (
        ("data", 'T'),
    )


class UInt16(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt16"
    _fields_ = (
        ("data", 'S'),
    )


class UInt16MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt16MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'S')),
    )


class UInt32(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt32"
    _fields_ = (
        ("data", 'I'),
    )


class UInt32MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt32MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'I')),
    )


class UInt64(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt64"
    _fields_ = (
        ("data", 'L'),
    )


class UInt64MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt64MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'L')),
    )


class UInt8(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt8"
    _fields_ = (
        ("data", 'o'),
    )


class UInt8MultiArray(Msg):
    _package_ = "std_msgs"
    _kind_ = "msg"
    _name_ = "UInt8MultiArray"
    _fields_ = (
        ("layout", MultiArrayLayout),
        ("data", ('q', 'o')),
    )
