"""SnakeROS message definitions for ``std_srvs``.

Generated by tools/snakeros_gen.py -- do not edit by hand.
"""

from ._base import Msg

class Empty_Request(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Empty_Request"
    _fields_ = ()


class Empty_Response(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Empty_Response"
    _fields_ = ()


class SetBool_Request(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "SetBool_Request"
    _fields_ = (
        ("data", 'b'),
    )


class SetBool_Response(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "SetBool_Response"
    _fields_ = (
        ("success", 'b'),
        ("message", 'T'),
    )


class Trigger_Request(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Trigger_Request"
    _fields_ = (
        ("success", 'b'),
        ("message", 'T'),
    )


class Trigger_Response(Msg):
    _package_ = "std_srvs"
    _kind_ = "srv"
    _name_ = "Trigger_Response"
    _fields_ = ()
